/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymanagementsystem.allframe;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JPanel;

/**
 *
 * @author jubel
 */
public class AdminMainForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    StudentRegForm studentRegForm;
    StudentInfoPanel studentInfoPanel;
    CourseFormPanel courseFormPanel;
    TeacherRegForm teacherRegForm;
    TeacherInfoPanel teacherInfoPanel;
    EmployeeRegistration employeeRegistration;
    EmployeeInfoPanel employeeInfoPanel;
    
    GridBagLayout grid;
    
    public AdminMainForm() throws SQLException {
        initComponents();
        addRightPanel();
      
    }
    
    public void addRightPanel() throws SQLException{
        studentRegForm = new StudentRegForm();
        studentInfoPanel = new StudentInfoPanel();
        courseFormPanel = new CourseFormPanel();
        teacherRegForm = new TeacherRegForm();
        teacherInfoPanel = new TeacherInfoPanel();
        employeeRegistration = new EmployeeRegistration();
        employeeInfoPanel = new EmployeeInfoPanel();
        grid = new GridBagLayout();
        adminMainRightPanel.setLayout(grid);
        GridBagConstraints gc = new GridBagConstraints();
        gc.gridx = 0;
        gc.gridy = 0;
        adminMainRightPanel.add(studentRegForm,gc);
        adminMainRightPanel.add(studentInfoPanel,gc);
        adminMainRightPanel.add(courseFormPanel,gc);
        adminMainRightPanel.add(teacherRegForm,gc);
        adminMainRightPanel.add(teacherInfoPanel,gc);
        adminMainRightPanel.add(employeeRegistration,gc);
        adminMainRightPanel.add(employeeInfoPanel,gc);
        
        studentRegForm.setVisible(false);
        studentInfoPanel.setVisible(false);
        courseFormPanel.setVisible(false);
        teacherRegForm.setVisible(false);
        teacherInfoPanel.setVisible(false);
        employeeRegistration.setVisible(false);
        employeeInfoPanel.setVisible(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        studentRegBtn = new javax.swing.JButton();
        teacherRegistrationBtn = new javax.swing.JButton();
        courseBtn = new javax.swing.JButton();
        employeeRegBtn1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        studentBtn = new javax.swing.JButton();
        teacherBtn = new javax.swing.JButton();
        employeeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        adminMainRightPanel = new javax.swing.JPanel();
        pixLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(209, 70));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentRegBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentRegBtn.setForeground(new java.awt.Color(51, 0, 0));
        studentRegBtn.setText("Student Registration");
        studentRegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRegBtnActionPerformed(evt);
            }
        });
        jPanel3.add(studentRegBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 41));

        teacherRegistrationBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        teacherRegistrationBtn.setForeground(new java.awt.Color(51, 0, 0));
        teacherRegistrationBtn.setText("Teacher Registration");
        teacherRegistrationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherRegistrationBtnActionPerformed(evt);
            }
        });
        jPanel3.add(teacherRegistrationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 105, 180, 41));

        courseBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        courseBtn.setForeground(new java.awt.Color(51, 0, 0));
        courseBtn.setText("Course");
        courseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseBtnActionPerformed(evt);
            }
        });
        jPanel3.add(courseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 30));

        employeeRegBtn1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        employeeRegBtn1.setForeground(new java.awt.Color(51, 0, 0));
        employeeRegBtn1.setText("Employee Registration");
        employeeRegBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeRegBtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(employeeRegBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 41));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 253));

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentBtn.setForeground(new java.awt.Color(0, 0, 51));
        studentBtn.setText("Student");
        studentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentBtnActionPerformed(evt);
            }
        });
        jPanel4.add(studentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 51, 170, 32));

        teacherBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        teacherBtn.setForeground(new java.awt.Color(0, 0, 51));
        teacherBtn.setText("Teacher");
        teacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherBtnActionPerformed(evt);
            }
        });
        jPanel4.add(teacherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 109, 168, 32));

        employeeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        employeeBtn.setForeground(new java.awt.Color(0, 0, 51));
        employeeBtn.setText("Employee");
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });
        jPanel4.add(employeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 159, 168, 32));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitymanagementsystem/icon/Sign Out_48px.png"))); // NOI18N
        jLabel1.setText("SignOut");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 253, 210, 250));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        adminMainRightPanel.setBackground(new java.awt.Color(0, 153, 204));
        adminMainRightPanel.setMinimumSize(new java.awt.Dimension(680, 503));
        adminMainRightPanel.setLayout(new java.awt.GridLayout(1, 0));

        pixLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitymanagementsystem/icon/newDiu.jpg"))); // NOI18N
        adminMainRightPanel.add(pixLabel);

        jPanel1.add(adminMainRightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 0, 680, 503));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void studentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBtnActionPerformed
        // TODO add your handling code here:
        studentInfoPanel.fillCourseCombobox();
        panelDisplayManage(studentInfoPanel);
        
    }//GEN-LAST:event_studentBtnActionPerformed

    public void panelDisplayManage(JPanel p){
        studentRegForm.setVisible(false);
        studentInfoPanel.setVisible(false);
        courseFormPanel.setVisible(false);
        teacherRegForm.setVisible(false);
        teacherInfoPanel.setVisible(false);
        employeeRegistration.setVisible(false);
        employeeInfoPanel.setVisible(false);
        p.setVisible(true);
        
    }
    private void teacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherBtnActionPerformed
        // TODO add your handling code here:
        teacherInfoPanel.fillCourseCombobox();
        panelDisplayManage(teacherInfoPanel);
    }//GEN-LAST:event_teacherBtnActionPerformed

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        // TODO add your handling code here:
        pixLabel.setVisible(false);
        panelDisplayManage(employeeInfoPanel);
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void teacherRegistrationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherRegistrationBtnActionPerformed
        // TODO add your handling code here:
        pixLabel.setVisible(false);
        panelDisplayManage(teacherRegForm);
        
    }//GEN-LAST:event_teacherRegistrationBtnActionPerformed

    private void courseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseBtnActionPerformed
        // TODO add your handling code here:
        pixLabel.setVisible(false);
        panelDisplayManage(courseFormPanel);
        
    }//GEN-LAST:event_courseBtnActionPerformed

    private void studentRegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRegBtnActionPerformed
        // TODO add your handling code here:
        pixLabel.setVisible(false);
         panelDisplayManage(studentRegForm);
    }//GEN-LAST:event_studentRegBtnActionPerformed

    private void employeeRegBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeRegBtn1ActionPerformed
        // TODO add your handling code here:
        pixLabel.setVisible(false);
        panelDisplayManage(employeeRegistration);
        
    }//GEN-LAST:event_employeeRegBtn1ActionPerformed

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
     
         // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel1KeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
          
        LogInForm form = null;
        try {
            form = new LogInForm();
        } catch (SQLException ex) {
            Logger.getLogger(AdminMainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminMainForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminMainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminMainRightPanel;
    private javax.swing.JButton courseBtn;
    private javax.swing.JButton employeeBtn;
    private javax.swing.JButton employeeRegBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel pixLabel;
    private javax.swing.JButton studentBtn;
    private javax.swing.JButton studentRegBtn;
    private javax.swing.JButton teacherBtn;
    private javax.swing.JButton teacherRegistrationBtn;
    // End of variables declaration//GEN-END:variables
}
