/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymanagementsystem.allframe;

/**
 *
 * @author jubel
 */
public class Format extends javax.swing.JPanel {

    /**
     * Creates new form StudentRegForm
     */
    public Format() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        adminId = new javax.swing.JTextField();
        adminName = new javax.swing.JTextField();
        adminEmail = new javax.swing.JTextField();
        femaleRadioBtn = new javax.swing.JRadioButton();
        maleRadioBtn = new javax.swing.JRadioButton();
        adminComboBox = new javax.swing.JComboBox<>();
        adminPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(680, 506));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 110, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Type");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Admin Registration");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 223, 36));
        add(adminId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 204, 33));
        add(adminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 204, 33));
        add(adminEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 204, 33));

        gender.add(femaleRadioBtn);
        femaleRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        femaleRadioBtn.setText("Female");
        femaleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioBtnActionPerformed(evt);
            }
        });
        add(femaleRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 100, 30));

        gender.add(maleRadioBtn);
        maleRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maleRadioBtn.setText("Male");
        add(maleRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 90, 30));

        adminComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Main", "Local" }));
        add(adminComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 200, 30));
        add(adminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 200, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 51));
        jButton1.setText("ADD");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void femaleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adminComboBox;
    private javax.swing.JTextField adminEmail;
    private javax.swing.JTextField adminId;
    private javax.swing.JTextField adminName;
    private javax.swing.JPasswordField adminPassword;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton maleRadioBtn;
    // End of variables declaration//GEN-END:variables
}
